services:
  app:
    image: python:3.9
    container_name: app_container
    volumes:
      - .:/app
    working_dir: /app
    command: python app.py
    ports:
      - "5000:5000"

  db:
    image: postgres:13
    container_name: db_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"