version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cosechas
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

    ports:
      - "5432:5432"
    networks:
      - mynetwork

volumes:
  db_data:
    driver: local
networks:
  mynetwork:
    driver: bridge